/* Sound: everything the app plays, and the rules for when it stays quiet.
 *
 * The samples are generated by tools/build_sounds.py -- none of them is a
 * downloaded file, so there is no licence to track and no upstream that can
 * change under a rebuild. What this file owns is the behaviour: what is worth
 * a sound, how loud, and how not to become annoying.
 *
 * Off by default, and that is not a limitation. An app that starts making
 * noises the first time you open it is an app you mute, and a practice tool
 * that beeps at you while you think is worse than a silent one. The switch
 * lives in Settings.
 *
 * The keyboard comes in two packs, and they are the two mechanical keyboards
 * worth imitating by ear. A pack is an instrument, not a volume: `creamy` is
 * the lubed board -- a low, rounded body with the click filtered down and
 * buried under it -- and `clicky` is the blue-switch board, a short bright
 * click on the press and a second, quieter one on the release. Only the
 * keystrokes change between them; the interface ticks and the verdicts are the
 * app's own voice, and a button that sounded different depending on how you
 * had set the keyboard would be incoherent.
 *
 * Everything the app itself says is deliberately quieter than the typing it
 * sits under. That is a property of the samples, not a setting: the generator
 * low-passes every non-keyboard file and writes it at a lower level, so
 * turning the volume up to hear the interface would also make the keyboard
 * deafening.
 *
 * The browser will not start an audio context before the user has interacted
 * with the page, so the context is created on the click that turns sound on
 * and resumed on the first pointer or key event afterwards. Everything below
 * checks `context` before it touches it, so a context that never arrives
 * reduces the app to a silent one rather than a broken one.
 */

const Sound = (() => {
  /* Every sample, written as the file it is, with the switch that silences it.
   *
   * The extension is here rather than stripped because this list is the
   * contract: test_api.py diffs it against the generator in
   * tools/build_sounds.py in both directions, because a name that drifts on
   * one side plays nothing, and playing nothing looks exactly like sound being
   * switched off. Everything below works in bare names. */
  const SAMPLES = {
    "key-creamy.wav": "typing",
    "key-creamy-space.wav": "typing",
    "key-creamy-delete.wav": "typing",
    "key-clicky.wav": "typing",
    "key-clicky-space.wav": "typing",
    "key-clicky-delete.wav": "typing",
    "tap.wav": "ui",
    "toggle.wav": "ui",
    "cue.wav": "ui",
    "open.wav": "ui",
    "close.wav": "ui",
    "pass.wav": "verdict",
    "fail.wav": "verdict",
    "trophy.wav": "awards",
  };

  const FILES = {};
  Object.keys(SAMPLES).forEach((file) => {
    FILES[file.replace(/\.wav$/, "")] = SAMPLES[file];
  });

  /* The two keyboards. The three keystrokes are named apart from the file they
   * play so that one pack can be swapped for another without the rest of the
   * app knowing a pack exists. */
  const PACKS = {
    creamy: {
      name: "Creamy",
      note: "Lubed and low. The body carries the keystroke and the click stays under it.",
      keys: {
        key: "key-creamy",
        "key-space": "key-creamy-space",
        "key-delete": "key-creamy-delete",
      },
    },
    clicky: {
      name: "Clicky",
      note: "A bright click on every press, and a second one as the key comes back up.",
      keys: {
        key: "key-clicky",
        "key-space": "key-clicky-space",
        "key-delete": "key-clicky-delete",
      },
    },
  };

  const STORAGE_KEY = "cbp.sound.v1";
  const DEFAULTS = {
    on: false,        // the master switch
    typing: true,     // the keyboard under the editor
    ui: true,         // buttons, panels, hints
    verdict: true,    // a run passing or failing
    awards: true,     // a trophy landing
    pack: "creamy",   // which keyboard
    volume: 0.6,
  };

  /* Two keystrokes closer together than this share one sample. Held-down keys
     repeat far faster than anyone types, and a burst of the same click at
     40 a second stops being a keyboard and starts being a rattle. */
  const TYPING_GAP_MS = 26;

  let context = null;
  let master = null;
  let buffers = new Map();
  let loading = new Map();
  let lastTyping = 0;
  let armed = false;
  let pending = false;
  let settings = load();

  /* Reads go through Store when it is present, because the app's settings live
   * on the server rather than in this origin: the port is ephemeral, so a
   * localStorage key written by one launch belongs to an origin the next
   * launch never sees again. Store falls back to localStorage on its own, and
   * so does this, so a plain browser without the module still works. */
  function readRaw() {
    try {
      if (window.Store) return Store.get(STORAGE_KEY);
      return localStorage.getItem(STORAGE_KEY);
    } catch (e) {
      return null;
    }
  }

  function load() {
    try {
      const stored = JSON.parse(readRaw() || "null");
      const merged = Object.assign({}, DEFAULTS, stored || {});
      if (!PACKS[merged.pack]) merged.pack = DEFAULTS.pack;
      return merged;
    } catch (e) {
      return Object.assign({}, DEFAULTS);
    }
  }

  /* Bring the context up as soon as the browser will allow it, if sound is
     supposed to be on.
   *
   * This is the whole reason a restored setting used to look like it had not
   * been saved. The context is created in exactly one place -- `unlock` -- and
   * `unlock` used to be reachable only from `update`, on the transition from
   * off to on. So a launch that restored `on: true` came up with the right
   * setting and no AudioContext at all: the switch read as on, the samples
   * never loaded, and every `play` returned false at its `if (!context)` guard.
   * Toggling off and on again fixed it, because that is the one path that did
   * call `unlock`, which is exactly how this presented as a saving bug when
   * nothing was wrong with the saving.
   *
   * A context cannot be created before a user gesture, so this arms a one-shot
   * listener rather than trying immediately. The gesture that fires it is
   * itself the first thing the user does after launch, so the wait is not
   * perceptible and there is no case where sound is on but the app is waiting
   * for permission it will not ask for.
   */
  /* The armed listener is a stable module-scope reference so it can be removed
     again; a closure created inside `armUnlock` could only ever be added. */
  const gesture = () => unlock();

  function armUnlock() {
    if (!settings.on) return;
    if (context || armed) return;
    if (!AudioContextClass()) return;
    armed = true;

    // Capture phase, and once: this has to beat the pointerdown that plays the
    // first tick, or that tick is the one sound that never plays.
    document.addEventListener("pointerdown", gesture, true);
    document.addEventListener("keydown", gesture, true);

    // And again, for an app that was launched and then left alone: a WebView
    // counts a focus or visibility change as an interaction on some platforms,
    // and it costs nothing to listen for one.
    document.addEventListener("visibilitychange", gesture, true);
    window.addEventListener("focus", gesture, true);
  }

  function disarmUnlock() {
    if (!armed) return;
    armed = false;
    document.removeEventListener("pointerdown", gesture, true);
    document.removeEventListener("keydown", gesture, true);
    document.removeEventListener("visibilitychange", gesture, true);
    window.removeEventListener("focus", gesture, true);
  }

  function save() {
    const value = JSON.stringify(settings);
    try {
      if (window.Store) Store.set(STORAGE_KEY, value);
      else localStorage.setItem(STORAGE_KEY, value);
    } catch (e) { /* ignore */ }
  }

  function AudioContextClass() {
    return window.AudioContext || window.webkitAudioContext || null;
  }

  function pack() {
    return PACKS[settings.pack] || PACKS[DEFAULTS.pack];
  }

  /* The bare name of the file a logical name plays. Keystrokes follow the
     chosen pack and everything else is its own sample, so a caller that wants
     to preview a switch can ask for the right clip rather than guessing -- the
     typing switch has to preview the pack you are about to hear, not the
     default one. */
  function sampleFor(name) {
    return pack().keys[name] || name;
  }

  /* Create the context and start loading the samples. Called from the click
     that enables sound, which is the gesture the browser is waiting for. */
  function unlock() {
    const Klass = AudioContextClass();
    if (!Klass) return false;
    if (!context) {
      try {
        context = new Klass();
      } catch (e) {
        return false;
      }
      master = context.createGain();
      master.gain.value = settings.volume;
      master.connect(context.destination);
    }
    if (context.state === "suspended") context.resume().catch(() => {});
    warm();
    return true;
  }

  /* Load every sample now rather than at the moment it is needed: decoding a
     buffer takes long enough that the first keystroke would be silent. Both
     packs are loaded, which is about 20 KB of wav, so switching keyboard is
     instant instead of silent for the first word. */
  function warm() {
    Object.keys(FILES).forEach(loadBuffer);
  }

  function loadBuffer(name) {
    if (loading.has(name)) return loading.get(name);
    if (!context) return Promise.resolve(null);
    const request = fetch("sounds/" + name + ".wav")
      .then((response) => response.arrayBuffer())
      .then((bytes) => context.decodeAudioData(bytes))
      .then((buffer) => {
        buffers.set(name, buffer);
        return buffer;
      })
      .catch(() => null);
    loading.set(name, request);
    return request;
  }

  function allowed(name) {
    if (!settings.on) return false;
    const category = FILES[name];
    return Boolean(category) && settings[category] !== false;
  }

  /* Play one sample. `rate` shifts the pitch and the length together, which on
     a click shorter than 60 ms is exactly the variation a real keyboard has;
     `gain` is for the sounds that need to sit under another one.
   *
   * A sample that has not finished decoding is played as soon as it has, but
   * only the first time. Decoding takes long enough that the very first sound
   * of a session would otherwise be dropped, and the first sound is the one a
   * person is listening for when they ask whether sound is working. Queuing it
   * is deliberately limited to a single pending sound: a burst of typing that
   * arrived before the samples were ready must not turn into a delayed volley
   * when they land, which is the failure a general queue would cause. */
  function play(name, options) {
    const file = sampleFor(name);
    if (!allowed(file)) return false;
    if (!context) return false;
    const buffer = buffers.get(file);
    if (!buffer) {
      // Only the first one is deferred. `pending` is a latch rather than a
      // queue: a paragraph typed before the samples are decoded must not arrive
      // as a delayed volley when they land.
      if (pending) { loadBuffer(file); return false; }
      pending = true;
      loadBuffer(file).then((decoded) => {
        pending = false;
        if (decoded) start(decoded, options);
      });
      return false;
    }

    const opts = options || {};
    return start(buffer, opts);
  }

  /* Schedule one already-decoded buffer. Split out of `play` so the deferred
     first sound and the immediate ones go through identical code, rather than
     being two implementations of "make a noise" that drift apart. */
  function start(buffer, opts) {
    if (!context || !buffer) return false;
    const source = context.createBufferSource();
    source.buffer = buffer;
    source.playbackRate.value = (opts && opts.rate) || 1;

    const gain = context.createGain();
    gain.gain.value = opts && opts.gain !== undefined ? opts.gain : 1;

    source.connect(gain);
    gain.connect(master);
    try {
      source.start();
    } catch (e) {
      return false;
    }
    return true;
  }

  /* A keystroke. Characters, space and enter, and delete each have their own
     sample -- the three keys that feel different under your fingers -- and
     every one of them is detuned slightly, so a paragraph does not sound like
     a machine gun. The rate spread is deliberately narrow: the creamy pack is
     already pitched low, and a wide spread would walk it into the room next
     door. */
  function type(base) {
    if (!allowed(sampleFor(base))) return false;
    const now = performance.now();
    if (now - lastTyping < TYPING_GAP_MS) return false;
    lastTyping = now;
    return play(base, {
      rate: 0.94 + Math.random() * 0.13,
      gain: 0.75 + Math.random() * 0.25,
    });
  }

  function settingsFor() {
    return Object.assign({}, settings);
  }

  /* Re-read the persisted settings and apply them. Called once the store has
     hydrated from the server, which happens after this file is parsed; until
     then the module runs on its defaults. It also re-applies the master gain,
     because the volume may have changed underneath a context that already
     exists. */
  function reload() {
    settings = load();
    if (master) master.gain.value = settings.volume;
    // The restored setting may say sound is on, in which case the context has
    // to be brought up on the first gesture. Without this the app came up
    // reading as enabled and silent.
    if (settings.on) armUnlock(); else disarmUnlock();
    return settingsFor();
  }

  /* Change one or more settings. Turning the master switch on returns whether
     an audio context actually came up, so the caller can tell the user when
     their setup has no audio rather than leaving them pressing a dead switch.
     An unknown pack is ignored rather than stored, so a hand-edited or stale
     localStorage value cannot leave the keyboard in a state with no files. */
  function update(patch) {
    const before = settings.on;
    const clean = Object.assign({}, patch);
    if ("pack" in clean && !PACKS[clean.pack]) delete clean.pack;
    settings = Object.assign({}, settings, clean);
    if (master) master.gain.value = settings.volume;
    save();
    if (settings.on && !before) return unlock();
    // Turning sound off, or changing a switch while it is already on, has to
    // leave the armed listener in the right state. An off switch with a
    // pending unlock would create a context for a session that asked for
    // silence.
    if (settings.on) armUnlock(); else disarmUnlock();
    return true;
  }

  return {
    play,
    type,
    update,
    settingsFor,
    reload,
    sampleFor,
    /* The packs, for the settings panel to render. Handed over as a copy so a
       rendering mistake cannot edit the instruments. */
    packs: () => Object.keys(PACKS).map((id) =>
      ({ id, name: PACKS[id].name, note: PACKS[id].note })),
    unlock: () => (settings.on ? unlock() : false),
    /* Whether this build can make a sound at all, for the settings panel to
       say so instead of offering a switch that cannot work. */
    available: () => Boolean(AudioContextClass()),
  };
})();
